version: "2"
services: 
  graphite:
    build: ./graphiteconfig
    restart: always
    ports:
        - "8080:80"
        - "8125:8125/udp"
        - "8126:8126"
        - "2003:2003"
        - "2004:2004"
    volumes: #Point to NDVP or local volumes
        - graphite-db-dev:/opt/graphite/storage/whisper
        #- /data/graphite-db:/opt/graphite/storage/whisper #This is a local volume
    networks:
        - net_sfcollector
  grafana:
    build: ./grafana
    restart: always
    ports:
        - "80:3000"
    volumes: #Point to NDVP or local volumes
        - grafana-dev:/var/lib/grafana
        #- grafana-conf:/etc/grafana
        #- /data/grafana:/var/lib/grafana #This is a local volume
    networks:
        - net_sfcollector
    environment: 
        - GF_SECURITY_ADMIN_PASSWORD=<your password> #Grafana password
        - GF_SMTP_ENABLED=true                       #Enable SMTP (optional)
        - GF_SMTP_HOST=smtp.gmail.com:465            #SMTP server (optional)
        - GF_SMTP_USER=<email address>               #SMTP email account (optional)
        - GF_SMTP_PASSWORD=<email password>          #SMTP email password (optional)
        - GF_SMTP_SKIP_VERIFY=true                   #Skip email verification (optional)

  sfcollector-alpine:
    build: ./collector-alpine
    restart: always
    networks: 
        - net_sfcollector
  
  vsphere-collector:
    build: ./vsphere-graphite
    restart: always
    networks:
        - net_sfcollector
    depends_on: 
        - graphite

networks:
  net_sfcollector:
    driver: bridge

volumes:
  graphite-db-dev:
    external: true
  #grafana-conf:
  #  external: true
  grafana-dev:
    external: true

