version: "2"
services: 
  graphite:
    build: ./graphiteconfig
    restart: always
    ports:
        - "8080:80"
        - "8125:8125/udp"
        - "8126:8126"
        - "2003:2003"
        - "2004:2004"
    volumes: #Point to NDVP or local volumes
        - graphite-db:/opt/graphite/storage/whisper
        #- /data/graphite-db:/opt/graphite/storage/whisper #This is a local volume
    networks:
        - net_sfcollector
  grafana:
    image: grafana/grafana
    restart: always
    ports:
        - "80:3000"
    volumes: #Point to NDVP or local volumes
        - grafana:/var/lib/grafana
        #- /data/grafana:/var/lib/grafana #This is a local volume
    networks:
        - net_sfcollector
    environment: #Set password for Grafana web interface
        - GF_SECURITY_ADMIN_PASSWORD=<your password>

  sfcollector-alpine:
    build: ./collector-alpine
    restart: always
    networks: 
        - net_sfcollector
  
  vsphere-collector:
    build: ./vsphere-graphite
    restart: always
    networks:
        - net_sfcollector
    depends_on: 
        - graphite

networks:
  net_sfcollector:
    driver: bridge

volumes:
  graphite-db:
    external: true
  grafana:
    external: true

