apiVersion: 1

datasources:
  - name: graphite-db
    type: graphite
    access: proxy
    orgId: 1
    url: http://10.193.136.36:8080
    isDefault: true
    version: 1
    editable: true
    basicAuth: false
